### ISSUE TITLE
Make iplookup a utility

### ISSUE THREAD

**Issue by shrayasr** [arindampradhan/py_projects#1]
For something like this that is small, why don't you consider making it a utility in itself? Add a [shebang](http://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts), take input from `stdin` and output to `stdout` in a way that is consumable by other unix utilities. You can find some tips to do that [here](http://monkey.org/~marius/unix-tools-hints.html)

That way this becomes a small util in itself. A small use case could be: 

```
$ iplookup <ip> | grep region 
```

or something like that.

**Comment by arindampradhan** [comment]
Made it a cmd tool.Hope not a over kill but lgtm ..!!
Hope you like it ;)

**Comment by shrayasr** [comment]
Woah. Looks good to me. A few comments on the code though: 
1. Use something like [docopt](http://docopt.org/) for parsing commandline arguments
2. Usually any long parameter name to a commandline util is prefixed by double dashes (`--`). Eg: 
   
   ```
   $ iplookup --region <ip>
   ```
   
   see [here](http://linuxcommand.org/wss0130.php) for some best practices w.r.t this
3. Fix usage of script [here](https://github.com/arindampradhan/py_projects/blob/master/iplookup/iplookup/iplookup.py#L8)

**Comment by arindampradhan** [comment]
Hi @shrayasr  ,I have updated the code,you can check it now...and thanks for the review.Let me know if you need any changes :)

**Comment by shrayasr** [comment]
LGTM :+1:
